defaults:
  - _self_
  - encoder: st
  # - faiss_index: default
ground_truth_path: "C:/Users/J C SINGLA/Downloads/External - take_home_challenge_(withJSONs)/take_home_challenge_(withJSONs)/document_questions.xlsx"
pdf_path: "C:/Users/J C SINGLA/Downloads/External - take_home_challenge_(withJSONs)/take_home_challenge_(withJSONs)/data/pdfs/"
data_name: "sherpa_paras_and_tables"
data_path: "C:/Users/J C SINGLA/Downloads/External - take_home_challenge_(withJSONs)/take_home_challenge_(withJSONs)/data/processed"
clean: False
idk: True
k: 10
recall_k: 10